version: ' 27.1.1'

services: 
    db: 
        container_name: postgres
        image: postgres:15.2
        restart: always
        env_file:
            - .env
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data

    volumes:
        postgres:
